// frontend/src/layouts/PublicLayout.tsx
import { useEffect, useState } from "react";
import { Link, Outlet } from "react-router-dom";
import { useAuth } from "../features/auth";
import { useCart } from "../features/cart";
import { getPublicStoreSettings } from "../features/admin/api/storeSettingsApi";
import type { StoreSettings } from "../features/admin/types/storeSettingsTypes";

export function PublicLayout() {
  const { session, logout } = useAuth();
  const { itemCount } = useCart();
  const [storeSettings, setStoreSettings] = useState<StoreSettings | null>(null);

  useEffect(() => {
    getPublicStoreSettings()
      .then(setStoreSettings)
      .catch(() => {});
  }, []);

  const getDashboardPath = () => {
    if (!session) return null;
    if (session.roles.includes("Admin")) return "/admin/dashboard";
    if (session.roles.includes("Manager")) return "/manager/dashboard";
    if (session.roles.includes("Seller")) return "/seller/dashboard";
    return null;
  };

  const dashboardPath = getDashboardPath();
  const storeName = storeSettings?.name || "Chợ Xanh";
  const hotline = storeSettings?.contactNumbers?.[0] || "1900 6868";

  return (
    <div className="public-layout">
      {/* Top Banner */}
      <div className="public-layout__top-banner">
        <div className="app-container banner-content">
          <span>🎉 Miễn phí giao hàng cho đơn từ 99.000đ</span>
          <span>Hotline: {hotline}</span>
        </div>
      </div>

      {/* Main Sticky Header */}
      <header className="public-layout__header glass-panel">
        <div className="app-container public-layout__header-content">
          <Link className="public-layout__brand" to="/">
            <span className="brand-icon">🥬</span> {storeName}
          </Link>
          
          <nav className="public-layout__navigation" aria-label="Account navigation">
            <Link className="nav-link" to="/">Sản phẩm</Link>
            <Link className="nav-link" to="/cart">Giỏ hàng ({itemCount})</Link>
            {session !== null && <Link className="nav-link" to="/account">Tài khoản</Link>}
            {dashboardPath && (
              <Link className="nav-link" to={dashboardPath}>Quản trị</Link>
            )}
            {session === null ? (
              <Link className="btn-primary hover-lift" to="/login">Đăng nhập</Link>
            ) : (
              <button className="btn-outline hover-lift" type="button" onClick={() => void logout()}>Đăng xuất</button>
            )}
          </nav>
        </div>
      </header>

      <main className="public-layout__main">
        <Outlet context={storeSettings} />
      </main>
      
      <footer className="public-layout__footer">
        <div className="app-container footer-content">
          <div className="footer-brand">
            <h3>{storeName}</h3>
            <p>Nông sản sạch & Nhu yếu phẩm tươi ngon mỗi ngày.</p>
            {storeSettings?.address && (
              <p className="footer-info" style={{ marginTop: 'var(--space-xs)', fontSize: '0.9rem' }}>
                📍 Địa chỉ: {storeSettings.address}
              </p>
            )}
            {storeSettings?.email && (
              <p className="footer-info" style={{ marginTop: '4px', fontSize: '0.9rem' }}>
                ✉️ Email: {storeSettings.email}
              </p>
            )}
          </div>
          <div className="footer-links">
            <Link to="/">Về chúng tôi</Link>
            <Link to="/">Cửa hàng</Link>
            <Link to="/">Liên hệ</Link>
          </div>
          <div className="footer-copyright">
            © 2026 {storeName}. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}

// angular-client/src/app/layouts/public-layout.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';
import { SessionService } from '../core/session.service';
import { CartStore } from '../core/cart.store';

@Component({
  selector: 'app-public-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="public-layout">
      <!-- Top Banner -->
      <div class="public-layout__top-banner">
        <div class="app-container banner-content">
          <span>🎉 Miễn phí giao hàng cho đơn từ 99.000đ</span>
          <span>Hotline: 1900 6868</span>
        </div>
      </div>

      <!-- Main Header -->
      <header class="public-layout__header glass-panel">
        <div class="app-container public-layout__header-content">
          <a class="public-layout__brand" routerLink="/">
            <span class="brand-icon">🥬</span> Chợ Xanh
          </a>
          <nav class="public-layout__navigation">
            <a class="nav-link" routerLink="/">Sản phẩm</a>
            <a class="nav-link" routerLink="/cart">Giỏ hàng ({{ cart.count() }})</a>
            
            @if (session.isAuthenticated()) {
              @if (session.hasRole('Admin')) {
                <a class="nav-link" routerLink="/admin/dashboard">Quản trị</a>
              } @else if (session.hasRole('Manager')) {
                <a class="nav-link" routerLink="/manager/dashboard">Quản lý</a>
              } @else if (session.hasRole('Seller')) {
                <a class="nav-link" routerLink="/seller/dashboard">Bán hàng</a>
              }
              <a class="nav-link" routerLink="/account">Tài khoản</a>
              <button class="btn-outline hover-lift" (click)="logout()">Đăng xuất</button>
            } @else {
              <a class="btn-primary hover-lift" routerLink="/login">Đăng nhập</a>
            }
          </nav>
        </div>
      </header>

      <!-- Main Content -->
      <main class="public-layout__main">
        <router-outlet />
      </main>

      <!-- Footer -->
      <footer class="public-layout__footer">
        <div class="app-container footer-content">
          <div class="footer-brand">
            <h3>Chợ Xanh</h3>
            <p>Nông sản sạch & nhu yếu phẩm tươi ngon mỗi ngày.</p>
          </div>
          <div class="footer-links">
            <a routerLink="/foundation">Về chúng tôi</a>
            <a routerLink="/">Cửa hàng</a>
            <a routerLink="/">Liên hệ</a>
          </div>
          <div class="footer-copyright">
            © 2026 Chợ Xanh. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  `
})
export class PublicLayoutComponent {
  readonly session = inject(SessionService);
  readonly cart = inject(CartStore);

  logout() {
    this.session.clearSession();
    this.cart.load();
  }
}
