// angular-client/src/app/pages/register-page.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { SessionService } from '../core/session.service';
import { errorMessage } from '../core/api-error';

@Component({
  selector: 'app-register-page',
  standalone: true,
  imports: [FormsModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="auth-page app-container">
      <div class="auth-card">
        <div class="auth-card__header">
          <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">🥬</div>
          <h1 class="auth-card__title">Đăng ký tài khoản</h1>
          <p class="auth-card__description">Tạo tài khoản mới để trải nghiệm mua sắm thực phẩm tiện lợi</p>
        </div>

        <form class="auth-form" (ngSubmit)="submit()">
          <label class="auth-form__field">
            <span>Địa chỉ Email</span>
            <input class="auth-form__input" type="email" name="email" [(ngModel)]="email" placeholder="example@domain.com" required />
          </label>

          <label class="auth-form__field">
            <span>Số điện thoại</span>
            <input class="auth-form__input" type="tel" name="phone" [(ngModel)]="phone" placeholder="0901234567" />
          </label>

          <label class="auth-form__field">
            <span>Mật khẩu</span>
            <input class="auth-form__input" type="password" name="password" [(ngModel)]="password" placeholder="••••••••" required />
          </label>

          @if (error()) {
            <div role="alert" class="auth-form__message">{{ error() }}</div>
          }

          <button type="submit" class="auth-form__submit hover-lift" [disabled]="loading()">
            {{ loading() ? 'Đang tạo tài khoản…' : 'Đăng ký' }}
          </button>
        </form>

        <div class="auth-card__footer">
          Đã có tài khoản? <a routerLink="/login">Đăng nhập</a>
        </div>
      </div>
    </div>
  `
})
export class RegisterPageComponent {
  private readonly api = inject(ApiService);
  private readonly session = inject(SessionService);
  private readonly router = inject(Router);

  email = '';
  phone = '';
  password = '';
  readonly error = signal('');
  readonly loading = signal(false);

  submit() {
    if (!this.email.trim() || !this.password) {
      this.error.set('Vui lòng nhập email và mật khẩu.');
      return;
    }

    this.loading.set(true);
    this.error.set('');

    this.api.register(this.email, this.phone, this.password).subscribe({
      next: res => {
        this.session.setSession(res);
        this.router.navigate(['/']);
      },
      error: e => {
        this.error.set(errorMessage(e));
        this.loading.set(false);
      }
    });
  }
}

// frontend/src/features/auth/pages/RegisterPage.tsx
import { useState } from "react";
import type { FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ApiError } from "../../../shared/api/apiClient";
import { useAuth } from "../hooks/useAuth";
import "./AuthPage.css";

export function RegisterPage() {
  const { register } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setErrorMessage("");

    if (!email.trim() && !phoneNumber.trim()) {
      setErrorMessage("Nhập ít nhất email hoặc số điện thoại để đăng nhập và nhận mã xác minh.");
      return;
    }

    if (password.length < 8) {
      setErrorMessage("Mật khẩu phải chứa ít nhất 8 ký tự.");
      return;
    }

    setIsSubmitting(true);
    try {
      const response = await register({
        email,
        phoneNumber,
        password
      });
      navigate(`/verify?userId=${encodeURIComponent(response.userId)}`, { replace: true });
    } catch (error) {
      setErrorMessage(error instanceof ApiError ? error.message : "Không thể tạo tài khoản vào lúc này.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <section className="auth-page app-container" aria-labelledby="register-heading">
      <div className="auth-card">
        <header className="auth-card__header">
          <h1 className="auth-card__title" id="register-heading">Đăng ký tài khoản</h1>
          <p className="auth-card__description">Nhập ít nhất email hoặc số điện thoại. Số điện thoại có thể dùng để đăng nhập khi không có email.</p>
        </header>

        <form className="auth-form" onSubmit={handleSubmit} noValidate>
          <label className="auth-form__field" htmlFor="register-email">
            <span>Địa chỉ email (tùy chọn)</span>
            <input className="auth-form__input" id="register-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" />
          </label>
          <label className="auth-form__field" htmlFor="register-phone">
            <span>Số điện thoại (tùy chọn, dùng để đăng nhập nếu không có email)</span>
            <input className="auth-form__input" id="register-phone" type="tel" value={phoneNumber} onChange={(event) => setPhoneNumber(event.target.value)} autoComplete="tel" />
          </label>
          <label className="auth-form__field" htmlFor="register-password">
            <span>Mật khẩu</span>
            <input
              className="auth-form__input"
              id="register-password"
              type="password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              autoComplete="new-password"
              required
            />
          </label>
          {errorMessage && <p className="auth-form__message" role="alert">{errorMessage}</p>}
          <button className="auth-form__submit" type="submit" disabled={isSubmitting}>
            {isSubmitting ? "Đang đăng ký…" : "Đăng ký"}
          </button>
        </form>
        <p className="auth-card__footer">Đã có tài khoản? <Link to="/login">Đăng nhập</Link>.</p>
      </div>
    </section>
  );
}
