// frontend/src/features/catalog/pages/CatalogPage.tsx
import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useOutletContext } from "react-router-dom";
import { getCategories, getProducts, searchSuggestions } from "../api/catalogApi";
import { ProductCard } from "../components/ProductCard";
import type { Category, PagedResponse, ProductListItem } from "../types/catalogTypes";
import type { StoreSettings } from "../../admin/types/storeSettingsTypes";
import "./CatalogPage.css";

export function CatalogPage() {
  const storeSettings = useOutletContext<StoreSettings | null>();
  const [categories, setCategories] = useState<Category[]>([]);
  const [products, setProducts] = useState<PagedResponse<ProductListItem> | null>(null);
  const [search, setSearch] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [page, setPage] = useState(1);
  const [error, setError] = useState("");
  const [suggestions, setSuggestions] = useState<ProductListItem[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [searchInput, setSearchInput] = useState("");
  const suggestionsRef = useRef<HTMLDivElement>(null);
  const searchBoxRef = useRef<HTMLDivElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const productsHeaderRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const [timeLeft, setTimeLeft] = useState(3 * 3600 + 12 * 60 + 45); // 03:12:45

  useEffect(() => {
    const timer = setInterval(() => {
      setTimeLeft((prev) => (prev > 0 ? prev - 1 : 3 * 3600 + 12 * 60 + 45));
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const hrs = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;
    return `${hrs.toString().padStart(2, "0")}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  useEffect(() => {
    let isMounted = true;
    void getCategories()
      .then((loadedCategories) => {
        if (isMounted) setCategories(loadedCategories);
      })
      .catch(() => {
        if (isMounted) setError("Không thể tải danh mục.");
      });
    return () => { isMounted = false; };
  }, []);

  useEffect(() => {
    let isMounted = true;
    void getProducts(search, categoryId, page)
      .then((loadedProducts) => {
        if (isMounted) setProducts(loadedProducts);
      })
      .catch(() => {
        if (isMounted) setError("Không thể tải sản phẩm.");
      });
    return () => { isMounted = false; };
  }, [search, categoryId, page]);

  // Debounced search suggestions
  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);

    if (searchInput.trim().length < 2) {
      setSuggestions([]);
      setShowSuggestions(false);
      return;
    }

    debounceRef.current = setTimeout(() => {
      void searchSuggestions(searchInput.trim())
        .then((result) => {
          setSuggestions(result.items);
          setShowSuggestions(true);
        })
        .catch(() => {
          setSuggestions([]);
          setShowSuggestions(true);
        });
    }, 300);

    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [searchInput]);

  // Close suggestions when clicking outside
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (searchBoxRef.current && !searchBoxRef.current.contains(event.target as Node)) {
        setShowSuggestions(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const handleSearchInputChange = (value: string) => {
    setSearchInput(value);
    setSearch(value);
    setPage(1);
  };

  const handleSuggestionClick = (slug: string) => {
    setShowSuggestions(false);
    navigate(`/products/${slug}`);
  };

  const handleCategorySelect = (id: string) => {
    setCategoryId(id);
    setPage(1);
    setTimeout(() => {
      if (productsHeaderRef.current) {
        const headerOffset = 90; // sticky header height + some margins
        const elementPosition = productsHeaderRef.current.getBoundingClientRect().top;
        const offsetPosition = elementPosition + window.scrollY - headerOffset;
        window.scrollTo({
          top: offsetPosition,
          behavior: "smooth"
        });
      }
    }, 100);
  };

  const formatPrice = (value: number) =>
    new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(value);

  return (
    <section className="catalog-page app-container" aria-labelledby="catalog-heading">
      <header className="catalog-page__hero">
        <p>{storeSettings?.name || "Tạp hóa chị Tỏ"}</p>
        <h1 id="catalog-heading">Nông sản sạch & Nhu yếu phẩm tươi ngon mỗi ngày</h1>
      </header>

      {/* Search Bar with Autocomplete */}
      <form className="catalog-page__search-bar" onSubmit={(event) => { event.preventDefault(); setShowSuggestions(false); setPage(1); }}>
        <div className="search-box" ref={searchBoxRef}>
          <svg className="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            id="search-input"
            value={searchInput}
            onChange={(event) => handleSearchInputChange(event.target.value)}
            onFocus={() => { if (suggestions.length > 0) setShowSuggestions(true); }}
            placeholder="Tìm rau củ, thịt cá, đồ dùng..."
            autoComplete="off"
          />
          {searchInput && (
            <button
              type="button"
              className="search-clear-btn"
              onClick={() => { setSearchInput(""); setSearch(""); setSuggestions([]); setShowSuggestions(false); setPage(1); }}
              aria-label="Xóa tìm kiếm"
            >
              ✕
            </button>
          )}

          {/* Suggestions Dropdown */}
          {showSuggestions && (
            <div className="search-suggestions" ref={suggestionsRef} role="listbox" aria-label="Gợi ý sản phẩm">
              {suggestions.length > 0 ? (
                <>
                  {suggestions.map((item) => (
                    <button
                      key={item.productId}
                      type="button"
                      className="suggestion-item"
                      role="option"
                      onClick={() => handleSuggestionClick(item.slug)}
                    >
                      <div className="suggestion-item__img">
                        {item.primaryImageUrl ? (
                          <img src={item.primaryImageUrl} alt="" loading="lazy" />
                        ) : (
                          <span className="suggestion-item__placeholder">📦</span>
                        )}
                      </div>
                      <div className="suggestion-item__info">
                        <span className="suggestion-item__name">{item.name}</span>
                        <span className="suggestion-item__category">{item.categoryName}</span>
                      </div>
                      <span className="suggestion-item__price">{formatPrice(item.sellingPrice)}</span>
                    </button>
                  ))}
                  <div className="suggestion-footer">
                    <span>Nhấn Enter để xem tất cả kết quả</span>
                  </div>
                </>
              ) : (
                <div className="suggestion-no-results">
                  Không tìm thấy sản phẩm
                </div>
              )}
            </div>
          )}
        </div>
      </form>

      {/* Visual Category Circular Icons */}
      <div className="catalog-page__category-nav" role="group" aria-label="Lọc theo danh mục">
        <button
          type="button"
          className={`cat-circle-btn ${categoryId === "" ? "active" : ""}`}
          onClick={() => handleCategorySelect("")}
        >
          <div className="cat-circle bg-surface">🌟</div>
          <span>Tất cả</span>
        </button>
        {categories.map((category) => {
          const categoryClass = getCategoryClass(category.name);
          const icon = getCategoryIcon(category.name);
          return (
            <button
              key={category.categoryId}
              type="button"
              className={`cat-circle-btn ${categoryId === category.categoryId ? "active" : ""}`}
              onClick={() => handleCategorySelect(category.categoryId)}
            >
              <div className={`cat-circle ${categoryClass}`}>{icon}</div>
              <span>{category.name}</span>
            </button>
          );
        })}
      </div>

      {/* Promotional Banner */}
      <div className="catalog-page__promo-banner">
        <div className="promo-text">
          <h2>Rau củ tươi mỗi sáng, giá rẻ mỗi ngày</h2>
          <p>Thu mua trực tiếp từ nông trại, giao trong 2 giờ</p>
          <button className="btn-promo hover-lift">Mua ngay</button>
        </div>
        <div className="promo-icon">🛒</div>
      </div>

      {/* Trust Badges */}
      <div className="catalog-page__trust-badges">
        <div className="trust-badge">
          <span className="trust-icon">💰</span>
          <p>Giá rẻ mỗi ngày</p>
        </div>
        <div className="trust-badge">
          <span className="trust-icon">🥬</span>
          <p>Tươi mới 100%</p>
        </div>
        <div className="trust-badge">
          <span className="trust-icon">⏱️</span>
          <p>Giao nhanh 2 giờ</p>
        </div>
        <div className="trust-badge">
          <span className="trust-icon">🏪</span>
          <p>Chỉ 1 cửa hàng duy nhất</p>
        </div>
      </div>

      {/* Flash Sale Mock Section */}
      <div className="catalog-page__flash-sale">
        <div className="flash-sale-header">
          <h2>Khung giờ vàng, giảm sâu</h2>
          <span className="countdown-timer">Kết thúc trong {formatTime(timeLeft)}</span>
        </div>
        <div className="flash-sale-grid">
          {/* Linked Items for Flash Sale */}
          <Link to="/products/ca-rot-da-lat" className="flash-sale-card hover-lift">
            <span className="discount-tag">-20%</span>
            <div className="fs-icon bg-success">🥕</div>
            <p className="fs-title">Cà rốt Đà Lạt 1kg</p>
            <p className="fs-price">16.000đ <s>20.000đ</s></p>
          </Link>
          <Link to="/products/trung-ga-vinamilk" className="flash-sale-card hover-lift">
            <span className="discount-tag">-15%</span>
            <div className="fs-icon bg-warning">🥚</div>
            <p className="fs-title">Trứng gà Vinamilk (Hộp)</p>
            <p className="fs-price">28.000đ <s>33.000đ</s></p>
          </Link>
          <Link to="/products/sua-th-true-milk" className="flash-sale-card hover-lift">
            <span className="discount-tag">-10%</span>
            <div className="fs-icon bg-info">🥛</div>
            <p className="fs-title">Sữa tươi TH True Milk 1L</p>
            <p className="fs-price">29.500đ <s>33.000đ</s></p>
          </Link>
          <Link to="/products/banh-cosy-marie" className="flash-sale-card hover-lift">
            <span className="discount-tag">-25%</span>
            <div className="fs-icon bg-surface">🍪</div>
            <p className="fs-title">Bánh quy Cosy Marie</p>
            <p className="fs-price">15.000đ <s>20.000đ</s></p>
          </Link>
        </div>
      </div>

      <div className="catalog-page__section-header" ref={productsHeaderRef}>
        <h2>{categoryId ? "Sản phẩm theo danh mục" : "Tất cả sản phẩm"}</h2>
      </div>

      {error ? <p role="alert" className="error-message">{error}</p> : null}

      {products && products.items.length === 0 ? (
        <p className="no-data" style={{ textAlign: "center", padding: "var(--space-xl)", color: "var(--color-text-muted)" }}>
          Không tìm thấy sản phẩm nào phù hợp với từ khóa tìm kiếm.
        </p>
      ) : (
        <div className="product-grid">
          {products?.items.map((product) => (
            <ProductCard key={product.productId} product={product} />
          ))}
        </div>
      )}

      {products && products.totalCount > products.pageSize ? (
        <nav className="catalog-page__pagination" aria-label="Phân trang">
          <button type="button" disabled={page === 1} onClick={() => setPage(page - 1)}>
            Trang trước
          </button>
          <span className="pagination-info">Trang {page} / {Math.ceil(products.totalCount / products.pageSize)}</span>
          <button
            type="button"
            disabled={page * products.pageSize >= products.totalCount}
            onClick={() => setPage(page + 1)}
          >
            Trang sau
          </button>
        </nav>
      ) : null}
    </section>
  );
}

function getCategoryClass(categoryName: string): string {
  const name = categoryName.toLowerCase();
  if (name.includes("rau") || name.includes("củ") || name.includes("nấm") || name.includes("veggie") || name.includes("vegetable")) {
    return "bg-success";
  }
  if (name.includes("trái") || name.includes("quả") || name.includes("fruit")) {
    return "bg-warning";
  }
  if (name.includes("thịt") || name.includes("cá") || name.includes("hải sản") || name.includes("meat") || name.includes("seafood")) {
    return "bg-danger";
  }
  if (name.includes("sữa") || name.includes("trứng") || name.includes("dairy") || name.includes("egg")) {
    return "bg-info";
  }
  if (name.includes("nước") || name.includes("uống") || name.includes("giải khát") || name.includes("beverage") || name.includes("drink")) {
    return "bg-violet";
  }
  if (name.includes("ăn vặt") || name.includes("bánh") || name.includes("kẹo") || name.includes("snack") || name.includes("sweet")) {
    return "bg-orange";
  }
  return "bg-surface";
}

function getCategoryIcon(categoryName: string): string {
  const name = categoryName.toLowerCase();
  if (name.includes("rau") || name.includes("củ") || name.includes("nấm") || name.includes("veggie") || name.includes("vegetable")) {
    return "🥬";
  }
  if (name.includes("trái") || name.includes("quả") || name.includes("fruit")) {
    return "🍎";
  }
  if (name.includes("thịt") || name.includes("cá") || name.includes("hải sản") || name.includes("meat") || name.includes("seafood")) {
    return "🥩";
  }
  if (name.includes("sữa") || name.includes("trứng") || name.includes("dairy") || name.includes("egg")) {
    return "🥛";
  }
  if (name.includes("nước") || name.includes("uống") || name.includes("giải khát") || name.includes("beverage") || name.includes("drink")) {
    return "🥤";
  }
  if (name.includes("ăn vặt") || name.includes("bánh") || name.includes("kẹo") || name.includes("snack") || name.includes("sweet")) {
    return "🍿";
  }
  return "📦";
}

// angular-client/src/app/pages/catalog-page.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, HostListener, inject, signal } from '@angular/core';
import { CurrencyPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { Category, PagedResponse, ProductListItem } from '../core/models';
import { errorMessage } from '../core/api-error';
import { ProductCardComponent } from '../components/product-card.component';

@Component({
  selector: 'app-catalog-page',
  standalone: true,
  imports: [FormsModule, CurrencyPipe, ProductCardComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="catalog-page app-container" aria-labelledby="catalog-heading">
      <!-- Hero Banner -->
      <header class="catalog-page__hero">
        <p>Tạp hóa chị Tỏ</p>
        <h1 id="catalog-heading">Nông sản sạch & Nhu yếu phẩm tươi ngon mỗi ngày</h1>
      </header>

      <!-- Search Bar with Autocomplete -->
      <form class="catalog-page__search-bar" (ngSubmit)="submitSearch()">
        <div class="search-box">
          <svg class="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            [ngModel]="searchInput()"
            (ngModelChange)="onSearchInputChange($event)"
            name="searchInput"
            placeholder="Tìm rau củ, thịt cá, đồ dùng..."
            autocomplete="off"
          />
          @if (searchInput()) {
            <button
              type="button"
              class="search-clear-btn"
              (click)="clearSearch()"
              aria-label="Xóa tìm kiếm"
            >
              ✕
            </button>
          }

          <!-- Suggestions Dropdown -->
          @if (showSuggestions()) {
            <div class="search-suggestions" role="listbox" aria-label="Gợi ý sản phẩm">
              @if (suggestions().length > 0) {
                @for (item of suggestions(); track item.productId) {
                  <button
                    type="button"
                    class="suggestion-item"
                    role="option"
                    (click)="goToProduct(item.slug)"
                  >
                    <div class="suggestion-item__img">
                      @if (api.imageUrl(item.primaryImageUrl); as image) {
                        <img [src]="image" alt="" loading="lazy" />
                      } @else {
                        <span class="suggestion-item__placeholder">📦</span>
                      }
                    </div>
                    <div class="suggestion-item__info">
                      <span class="suggestion-item__name">{{ item.name }}</span>
                      <span class="suggestion-item__category">{{ item.categoryName }}</span>
                    </div>
                    <span class="suggestion-item__price">{{ item.sellingPrice | currency:'VND':'symbol':'1.0-0' }}</span>
                  </button>
                }
                <div class="suggestion-footer">
                  <span>Nhấn Enter để xem tất cả kết quả</span>
                </div>
              } @else {
                <div class="suggestion-no-results">
                  Không tìm thấy sản phẩm
                </div>
              }
            </div>
          }
        </div>
      </form>

      <!-- Category Circular Navigation -->
      <div class="catalog-page__category-nav" role="group" aria-label="Lọc theo danh mục">
        <button
          type="button"
          class="cat-circle-btn"
          [class.active]="categoryId() === ''"
          (click)="selectCategory('')"
        >
          <div class="cat-circle bg-surface">🌟</div>
          <span>Tất cả</span>
        </button>
        @for (category of categories(); track category.categoryId) {
          <button
            type="button"
            class="cat-circle-btn"
            [class.active]="categoryId() === category.categoryId"
            (click)="selectCategory(category.categoryId)"
          >
            <div class="cat-circle" [class]="getCategoryBgClass(category.name)">
              {{ getCategoryIcon(category.name) }}
            </div>
            <span>{{ category.name }}</span>
          </button>
        }
      </div>

      <!-- Promotional Banner -->
      <div class="catalog-page__promo-banner">
        <div class="promo-text">
          <h2>Rau củ tươi mỗi sáng, giá rẻ mỗi ngày</h2>
          <p>Thu mua trực tiếp từ nông trại, giao trong 2 giờ</p>
          <button type="button" class="btn-promo hover-lift" (click)="selectCategory('')">Mua ngay</button>
        </div>
        <div class="promo-icon">🛒</div>
      </div>

      <!-- Trust Badges -->
      <div class="catalog-page__trust-badges">
        <div class="trust-badge">
          <span class="trust-icon">💰</span>
          <p>Giá rẻ mỗi ngày</p>
        </div>
        <div class="trust-badge">
          <span class="trust-icon">🥬</span>
          <p>Tươi mới 100%</p>
        </div>
        <div class="trust-badge">
          <span class="trust-icon">⏱️</span>
          <p>Giao nhanh 2 giờ</p>
        </div>
        <div class="trust-badge">
          <span class="trust-icon">🏪</span>
          <p>Chỉ 1 cửa hàng duy nhất</p>
        </div>
      </div>

      <!-- Flash Sale -->
      @if (promotions().length > 0) {
        <section class="catalog-page__flash-sale">
          <div class="flash-sale-header">
            <h2>Sản phẩm đang giảm giá</h2>
            <span class="countdown-timer">Khuyến mãi cực hot</span>
          </div>
          <div class="product-grid">
            @for (product of promotions(); track product.productId) {
              <app-product-card [product]="product" />
            }
          </div>
        </section>
      }

      <!-- Main Products Section -->
      <div class="catalog-page__section-header">
        <h2>{{ categoryId() ? 'Sản phẩm theo danh mục' : 'Tất cả sản phẩm' }}</h2>
      </div>

      @if (error()) {
        <p role="alert" class="error-message">{{ error() }}</p>
      } @else if (loading()) {
        <p class="no-data" style="text-align: center; padding: 2rem;">Đang tải sản phẩm…</p>
      } @else if (result()?.items?.length === 0) {
        <p class="no-data" style="text-align: center; padding: 2rem; color: var(--color-text-muted);">
          Không tìm thấy sản phẩm nào phù hợp với từ khóa tìm kiếm.
        </p>
      } @else {
        <div class="product-grid">
          @for (product of result()?.items ?? []; track product.productId) {
            <app-product-card [product]="product" />
          }
        </div>

        <!-- Pagination -->
        @if (result() && result()!.totalCount > result()!.pageSize) {
          <nav class="catalog-page__pagination" aria-label="Phân trang">
            <button
              type="button"
              [disabled]="page() === 1"
              (click)="changePage(page() - 1)"
            >
              Trang trước
            </button>
            <span class="pagination-info">
              Trang {{ page() }} / {{ totalPages() }}
            </span>
            <button
              type="button"
              [disabled]="page() * result()!.pageSize >= result()!.totalCount"
              (click)="changePage(page() + 1)"
            >
              Trang sau
            </button>
          </nav>
        }
      }
    </section>
  `
})
export class CatalogPageComponent {
  readonly api = inject(ApiService);
  readonly router = inject(Router);
  readonly elementRef = inject(ElementRef);

  readonly categories = signal<Category[]>([]);
  readonly result = signal<PagedResponse<ProductListItem> | null>(null);
  readonly promotions = signal<ProductListItem[]>([]);
  readonly suggestions = signal<ProductListItem[]>([]);
  readonly showSuggestions = signal(false);
  readonly loading = signal(true);
  readonly error = signal('');

  readonly searchInput = signal('');
  readonly search = signal('');
  readonly categoryId = signal('');
  readonly page = signal(1);

  private debounceTimer: any = null;

  constructor() {
    this.api.categories().subscribe({
      next: value => this.categories.set(value)
    });
    this.load();
    this.loadPromotions();
  }

  load() {
    this.loading.set(true);
    this.error.set('');
    this.api.products(this.search(), this.categoryId(), this.page()).subscribe({
      next: value => {
        this.result.set(value);
        this.loading.set(false);
      },
      error: e => {
        this.error.set(errorMessage(e));
        this.loading.set(false);
      }
    });
  }

  loadPromotions() {
    this.api.products('', '', 1, 100).subscribe({
      next: res => {
        const promos = res.items.filter(p => p.compareAtPrice !== null && p.compareAtPrice > p.sellingPrice);
        this.promotions.set(promos.slice(0, 4));
      }
    });
  }

  onSearchInputChange(value: string) {
    this.searchInput.set(value);
    this.search.set(value);
    this.page.set(1);

    if (this.debounceTimer) clearTimeout(this.debounceTimer);

    if (value.trim().length < 2) {
      this.suggestions.set([]);
      this.showSuggestions.set(false);
      return;
    }

    this.debounceTimer = setTimeout(() => {
      this.api.products(value.trim(), '', 1, 5).subscribe({
        next: res => {
          this.suggestions.set(res.items);
          this.showSuggestions.set(true);
        },
        error: () => {
          this.suggestions.set([]);
          this.showSuggestions.set(true);
        }
      });
    }, 300);
  }

  submitSearch() {
    this.showSuggestions.set(false);
    this.page.set(1);
    this.load();
  }

  clearSearch() {
    this.searchInput.set('');
    this.search.set('');
    this.suggestions.set([]);
    this.showSuggestions.set(false);
    this.page.set(1);
    this.load();
  }

  goToProduct(slug: string) {
    this.showSuggestions.set(false);
    this.router.navigate(['/products', slug]);
  }

  selectCategory(id: string) {
    this.categoryId.set(id);
    this.page.set(1);
    this.load();
  }

  changePage(newPage: number) {
    this.page.set(newPage);
    this.load();
    window.scrollTo({ top: 300, behavior: 'smooth' });
  }

  totalPages(): number {
    const res = this.result();
    if (!res) return 1;
    return Math.ceil(res.totalCount / res.pageSize);
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent) {
    if (!this.elementRef.nativeElement.contains(event.target)) {
      this.showSuggestions.set(false);
    }
  }

  getCategoryBgClass(name: string): string {
    const n = name.toLowerCase();
    if (n.includes('rau') || n.includes('củ')) return 'bg-success';
    if (n.includes('trái') || n.includes('quả')) return 'bg-warning';
    if (n.includes('thịt') || n.includes('cá')) return 'bg-danger';
    if (n.includes('sữa') || n.includes('trứng')) return 'bg-info';
    if (n.includes('nước') || n.includes('uống')) return 'bg-violet';
    if (n.includes('bánh') || n.includes('snack')) return 'bg-orange';
    return 'bg-surface';
  }

  getCategoryIcon(name: string): string {
    const n = name.toLowerCase();
    if (n.includes('rau') || n.includes('củ')) return '🥬';
    if (n.includes('trái') || n.includes('quả')) return '🍎';
    if (n.includes('thịt') || n.includes('cá')) return '🥩';
    if (n.includes('sữa') || n.includes('trứng')) return '🥛';
    if (n.includes('nước') || n.includes('uống')) return '🥤';
    if (n.includes('bánh') || n.includes('snack')) return '🍿';
    return '📦';
  }
}
